In [2]:
import torch

a = torch.arange(12).view(3, 4)
print(a)
b = torch.ones(1, 4).long()
print(b)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[1, 1, 1, 1]])


In [3]:
a[torch.tensor([0, 0])]

tensor([[0, 1, 2, 3],
        [0, 1, 2, 3]])

In [4]:
a.index_select(0, torch.tensor([0, 0]))

tensor([[0, 1, 2, 3],
        [0, 1, 2, 3]])

RuntimeError: shape '[1, 4]' is invalid for input of size 1